# Generated by Django 5.0.2 on 2024-03-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=600),
        ),
    ]
